# Generated by Django 2.0.7 on 2018-07-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('likes', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=120)),
            ],
        ),
    ]
